<ul id="MenuBar1" class="MenuBarHorizontal">
			<li><a href="main.php" title="Return to index page">Home</a></li>
			<li><a href="#" title="Exchanges Index" target="_blank" class="MenuBarItemSubmenu">Exchanges</a>
				<ul>
					<li><a href="addexchange.php">Add New</a></li>
					<li><a href="listexchanges.php?status=new">Approve New</a></li>
					<li><a href="listexchanges.php?status=active">Active Exchanges</a></li>
					<li><a href="listexchanges.php?status=inactive">Inactive Exchanges</a></li>
				</ul>
			</li>
			<li><a href="#" class="MenuBarItemSubmenu">Transactions</a>
				<ul>
					<li><a href="#">Enter Transaction</a></li>
					<li><a href="txlist.php">List Transactions</a></li>
				</ul>
			</li>
			<li><a class="MenuBarItemSubmenu" href="#">Rates</a>
				<ul>
					<li><a class="MenuBarItemSubmenu" href="#">List Currencies</a></li>
					<li><a href="#">List/Edit Rates</a></li>
				</ul>
			</li>
			<li><a href="#" class="MenuBarItemSubmenu">Statistics</a>
				<ul>
					<li><a href="#">Trading Statistics</a></li>
					<li><a href="#">Balance of Trade</a></li>
				</ul>
			</li>
			<li><a href="logout.php">Log Out</a></li>
		</ul>
