<ul id="MenuBar1" class="MenuBarHorizontal">
			<li><a href="main.php" title="Go to index page">Home</a></li>
			<li><a href="account.php" title="Edit my record" class="MenuBarItemSubmenu">My Record</a>
				<ul>
					<li><a href="account.php">Edit My Record</a></li>
					<li><a href="listexchanges.php">Remote Exchanges</a></li>
					<li><a href="main.php">Index Page</a></li>
				</ul>
			</li>
			<li><a href="#" title="Transaction functions" class="MenuBarItemSubmenu">Transactions</a>
				<ul>
					<li><a href="main.php">Enter Transaction</a></li>
					<li><a href="main.php">Balance</a></li>
					<li><a href="txlist.php">List Transactions</a></li>
				</ul>
			</li>
			<li><a class="MenuBarItemSubmenu" href="#">Rates</a>
				<ul>
					<li><a class="MenuBarItemSubmenu" href="listcurrencies.php">List Currencies</a></li>
					<li><a href="#">Conversion Rates</a></li>
				</ul>
			</li>
			<li><a href="#" class="MenuBarItemSubmenu">Statistics</a>
				<ul>
					<li><a href="#">Trading Statistics</a></li>
					<li><a href="#">Balance of Trade</a></li>
				</ul>
			</li>
			<li><a href="logout.php">Log Out</a></li>
		</ul>
